// data_people.go — the person catalog (D3 discover).
//
// Real film-history figures with short factual bios, real TMDB profile image
// paths (when TMDB has one; "" renders as JSON null) and real IMDb ids, plus
// the invented people behind the fictional shows. Ids are FAKE sequential
// 1..N (NOT real TMDB person ids). Credits are NOT written here: every
// person's CastCredits/CrewCredits are derived at init from the per-title
// cast and crew tables in data_credits.go (discLinkCredits), so one table
// owns who did what on which title.
package main

// discPersons holds the person catalog in id order.
var discPersons = []*DemoPerson{
	{
		ID:           1,
		Name:         "Buster Keaton",
		Biography:    "Joseph Frank Keaton, known professionally as Buster Keaton, was an American actor, comedian, film director, producer, screenwriter, and stunt performer. He is best known for his silent films, in which his trademark was physical comedy with a consistently stoic, deadpan expression.",
		Birthday:     "1895-10-04",
		Deathday:     "1966-02-01",
		PlaceOfBirth: "Piqua, Kansas, USA",
		ProfilePath:  "/kEybBFkO5AX83o3WKyNDfuvfVrn.jpg",
		KnownForDept: "Acting",
		Popularity:   35.2,
		Gender:       2,
		ImdbID:       "nm0000036",
		AlsoKnownAs:  []string{"Joseph Frank Keaton", "The Great Stone Face"},
	},
	{
		ID:           2,
		Name:         "Fritz Lang",
		Biography:    "Friedrich Christian Anton Lang was an Austrian-German-American filmmaker, screenwriter, and occasional film producer and actor. One of the best known practitioners of German Expressionism.",
		Birthday:     "1890-12-05",
		Deathday:     "1976-08-02",
		PlaceOfBirth: "Vienna, Austria-Hungary",
		ProfilePath:  "/9dz4PmFzlSyexldWrOXBLLpkBqB.jpg",
		KnownForDept: "Directing",
		Popularity:   28.9,
		Gender:       2,
		ImdbID:       "nm0000485",
		AlsoKnownAs:  []string{"Friedrich Christian Anton Lang"},
	},
	{
		ID:           3,
		Name:         "F.W. Murnau",
		Biography:    "Friedrich Wilhelm Murnau was a German film director who was a prominent figure during the Golden Age of Weimar cinema.",
		Birthday:     "1888-12-28",
		Deathday:     "1931-03-11",
		PlaceOfBirth: "Bielefeld, Germany",
		ProfilePath:  "/keLp43iiIkkllroUwExIJITeR7a.jpg",
		KnownForDept: "Directing",
		Popularity:   22.4,
		Gender:       2,
		ImdbID:       "nm0003638",
		AlsoKnownAs:  []string{"Friedrich Wilhelm Plumpe"},
	},
	{
		ID:           4,
		Name:         "George A. Romero",
		Biography:    "George Andrew Romero was an American-Canadian filmmaker, writer, and editor, best known for his series of zombie films. He is considered the father of the modern zombie genre.",
		Birthday:     "1940-02-04",
		Deathday:     "2017-07-16",
		PlaceOfBirth: "The Bronx, New York, USA",
		ProfilePath:  "/w2zVF92x149qK79ZxwUowcSp2c6.jpg",
		KnownForDept: "Directing",
		Popularity:   25.1,
		Gender:       2,
		ImdbID:       "nm0001681",
		AlsoKnownAs:  []string{"George Andrew Romero"},
	},
	{
		ID:           5,
		Name:         "Duane Jones",
		Biography:    "American actor and theatre director whose lead role as Ben in Night of the Living Dead was a landmark casting of a Black actor in a horror film.",
		Birthday:     "1936-02-02",
		Deathday:     "1988-07-22",
		PlaceOfBirth: "New York City, New York, USA",
		ProfilePath:  "/6IKcAo7UwByTM3U8awBBuJlHAQs.jpg",
		KnownForDept: "Acting",
		Popularity:   1.5,
		Gender:       2,
		ImdbID:       "nm0427977",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           6,
		Name:         "Judith O'Dea",
		Biography:    "American actress best known for playing Barbra in George A. Romero's Night of the Living Dead.",
		Birthday:     "1945-04-20",
		Deathday:     "",
		PlaceOfBirth: "Pittsburgh, Pennsylvania, USA",
		ProfilePath:  "/cCZfWRio05U5qVbQBfUgncdAMHJ.jpg",
		KnownForDept: "Acting",
		Popularity:   0.7,
		Gender:       1,
		ImdbID:       "nm0640621",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           7,
		Name:         "Karl Hardman",
		Biography:    "American actor and producer who played Harry Cooper in, and co-produced, Night of the Living Dead.",
		Birthday:     "1927-03-22",
		Deathday:     "2007-09-22",
		PlaceOfBirth: "Pittsburgh, Pennsylvania, USA",
		ProfilePath:  "/vs5xLO71stUS3Cn1UD1EWeGAa7b.jpg",
		KnownForDept: "Acting",
		Popularity:   0.7,
		Gender:       2,
		ImdbID:       "nm0362457",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           8,
		Name:         "John A. Russo",
		Biography:    "American screenwriter and author who co-wrote Night of the Living Dead with George A. Romero.",
		Birthday:     "1939-02-02",
		Deathday:     "",
		PlaceOfBirth: "",
		ProfilePath:  "",
		KnownForDept: "Writing",
		Popularity:   0.6,
		Gender:       2,
		ImdbID:       "nm0751652",
		AlsoKnownAs:  []string{"John Russo"},
	},
	{
		ID:           9,
		Name:         "Russell Streiner",
		Biography:    "American film producer and actor, a co-founder of Image Ten, who produced Night of the Living Dead and played Johnny in it.",
		Birthday:     "1940-02-06",
		Deathday:     "",
		PlaceOfBirth: "",
		ProfilePath:  "",
		KnownForDept: "Production",
		Popularity:   0.5,
		Gender:       2,
		ImdbID:       "nm0834183",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           10,
		Name:         "Max Schreck",
		Biography:    "German actor best remembered as Count Orlok in F.W. Murnau's Nosferatu.",
		Birthday:     "1879-09-06",
		Deathday:     "1936-02-20",
		PlaceOfBirth: "Berlin, Germany",
		ProfilePath:  "/uKVNFFt6VA8R7pp7HIPJF4e5PfX.jpg",
		KnownForDept: "Acting",
		Popularity:   2.2,
		Gender:       2,
		ImdbID:       "nm0775180",
		AlsoKnownAs:  []string{"Maximilian Schreck", "Friedrich Gustav Maximilian Schreck"},
	},
	{
		ID:           11,
		Name:         "Gustav von Wangenheim",
		Biography:    "German actor, director, and screenwriter who played Hutter in Nosferatu.",
		Birthday:     "1895-02-18",
		Deathday:     "1975-10-14",
		PlaceOfBirth: "Wiesbaden, Germany",
		ProfilePath:  "/5BQ07rsNY9z3IoN6sdwipoFoNWV.jpg",
		KnownForDept: "Acting",
		Popularity:   1.3,
		Gender:       2,
		ImdbID:       "nm0903194",
		AlsoKnownAs:  []string{"Gustav Adolf Freiherr von Wangenheim"},
	},
	{
		ID:           12,
		Name:         "Greta Schröder",
		Biography:    "German actress who played Ellen in Nosferatu.",
		Birthday:     "1892-06-27",
		Deathday:     "1980-06-08",
		PlaceOfBirth: "Düsseldorf, Germany",
		ProfilePath:  "/vkwD2LVM2QRD2a6auvq1K6Zpwd0.jpg",
		KnownForDept: "Acting",
		Popularity:   0.8,
		Gender:       1,
		ImdbID:       "nm0775659",
		AlsoKnownAs:  []string{"Greta Schroeder Mátray", "Margarethe \"Greta\" Schröder"},
	},
	{
		ID:           13,
		Name:         "Henrik Galeen",
		Biography:    "Austrian-born screenwriter and director of Weimar cinema who wrote the screenplay for Nosferatu.",
		Birthday:     "1881-01-07",
		Deathday:     "1949-07-30",
		PlaceOfBirth: "Lemberg, Galicia, Austria-Hungary [now Lviv, Ukraine]",
		ProfilePath:  "",
		KnownForDept: "Writing",
		Popularity:   0.9,
		Gender:       2,
		ImdbID:       "nm0301961",
		AlsoKnownAs:  []string{"Heinrich Wiesenberg"},
	},
	{
		ID:           14,
		Name:         "Albin Grau",
		Biography:    "German artist, architect, and occultist who co-founded Prana-Film and produced and designed Nosferatu.",
		Birthday:     "1894-12-22",
		Deathday:     "1971-03-27",
		PlaceOfBirth: "Berlin, Germany",
		ProfilePath:  "",
		KnownForDept: "Production",
		Popularity:   0.5,
		Gender:       2,
		ImdbID:       "nm0336057",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           15,
		Name:         "Cary Grant",
		Biography:    "English-born American actor, one of classic Hollywood's definitive leading men, known for screwball comedy and his films with Hitchcock.",
		Birthday:     "1904-01-18",
		Deathday:     "1986-11-29",
		PlaceOfBirth: "Horfield, Bristol, England, UK",
		ProfilePath:  "/lcNAirMFcyM7WIiCmaabjbNZVOJ.jpg",
		KnownForDept: "Acting",
		Popularity:   2.5,
		Gender:       2,
		ImdbID:       "nm0000026",
		AlsoKnownAs:  []string{"Archibald Alec Leach", "Archibald Leach"},
	},
	{
		ID:           16,
		Name:         "Rosalind Russell",
		Biography:    "American actress of stage and screen, celebrated for fast-talking comic roles such as Hildy Johnson in His Girl Friday.",
		Birthday:     "1907-06-04",
		Deathday:     "1976-11-28",
		PlaceOfBirth: "Waterbury, Connecticut, USA",
		ProfilePath:  "/rM7cjXZv9ikJ3QOOqK2muzMhHsE.jpg",
		KnownForDept: "Acting",
		Popularity:   1.3,
		Gender:       1,
		ImdbID:       "nm0751426",
		AlsoKnownAs:  []string{"Catherine Rosalind Russell "},
	},
	{
		ID:           17,
		Name:         "Ralph Bellamy",
		Biography:    "American actor with a long career on stage, film, and television, often cast as the affable man who loses the girl.",
		Birthday:     "1904-06-17",
		Deathday:     "1991-11-29",
		PlaceOfBirth: "Chicago, Illinois, USA",
		ProfilePath:  "/vC6cdrUUewgurTlVXt36eRAtQKb.jpg",
		KnownForDept: "Acting",
		Popularity:   3.2,
		Gender:       2,
		ImdbID:       "nm0000897",
		AlsoKnownAs:  []string{"Ralph Rexford Bellamy"},
	},
	{
		ID:           18,
		Name:         "Howard Hawks",
		Biography:    "American director and producer whose work spanned screwball comedy, film noir, westerns, and war films.",
		Birthday:     "1896-05-30",
		Deathday:     "1977-12-26",
		PlaceOfBirth: "Goshen, Indiana, USA",
		ProfilePath:  "/hG2oF9wZlqwGqP6EhG0qaN9Afg7.jpg",
		KnownForDept: "Directing",
		Popularity:   2.6,
		Gender:       2,
		ImdbID:       "nm0001328",
		AlsoKnownAs:  []string{"Howard Winchester Hawks"},
	},
	{
		ID:           19,
		Name:         "Charles Lederer",
		Biography:    "American screenwriter and director who adapted The Front Page into His Girl Friday.",
		Birthday:     "1906-12-31",
		Deathday:     "1976-03-05",
		PlaceOfBirth: "New York City, New York, USA",
		ProfilePath:  "/h8OpLegI7NkkfpbF7WFsQ3uYaW3.jpg",
		KnownForDept: "Writing",
		Popularity:   1.5,
		Gender:       2,
		ImdbID:       "nm0496468",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           20,
		Name:         "Ben Hecht",
		Biography:    "American screenwriter, playwright, and journalist; co-author of the play The Front Page, the basis of His Girl Friday.",
		Birthday:     "1894-02-28",
		Deathday:     "1964-04-18",
		PlaceOfBirth: "New York City, New York, USA",
		ProfilePath:  "/uYYvAfPiSx5BoWA0CrUS32p3qI5.jpg",
		KnownForDept: "Writing",
		Popularity:   2.6,
		Gender:       2,
		ImdbID:       "nm0372942",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           21,
		Name:         "Marion Mack",
		Biography:    "American actress and screenwriter who played Annabelle Lee opposite Buster Keaton in The General.",
		Birthday:     "1902-04-08",
		Deathday:     "1989-05-01",
		PlaceOfBirth: "Mammoth, Utah, USA",
		ProfilePath:  "/6J8gna8pbBwzseEEYAwvsmwOCLb.jpg",
		KnownForDept: "Acting",
		Popularity:   0.8,
		Gender:       1,
		ImdbID:       "nm0533045",
		AlsoKnownAs:  []string{"Elinor Lynn", "Joey Marion McCreery Lewyn"},
	},
	{
		ID:           22,
		Name:         "Glen Cavender",
		Biography:    "American actor of the silent era who played Captain Anderson in The General.",
		Birthday:     "1883-09-18",
		Deathday:     "1962-02-09",
		PlaceOfBirth: "Tucson, Arizona, USA",
		ProfilePath:  "/mkCWTmyWtInbtNiSkBaUU20DgXz.jpg",
		KnownForDept: "Acting",
		Popularity:   0.9,
		Gender:       2,
		ImdbID:       "nm0147070",
		AlsoKnownAs:  []string{"Glen W. Cavender", "Glenn Cavender"},
	},
	{
		ID:           23,
		Name:         "Clyde Bruckman",
		Biography:    "American screenwriter and director who co-directed The General with Buster Keaton.",
		Birthday:     "1894-06-30",
		Deathday:     "1955-01-04",
		PlaceOfBirth: "San Bernardino, California, USA",
		ProfilePath:  "/qS2v6oBeDALfrcqLvov7ITVPBeM.jpg",
		KnownForDept: "Writing",
		Popularity:   1.9,
		Gender:       2,
		ImdbID:       "nm0115669",
		AlsoKnownAs:  []string{" Clyde A. Bruckman"},
	},
	{
		ID:           24,
		Name:         "Al Boasberg",
		Biography:    "American comedy writer who contributed gags and titles to silent and early sound comedies, including The General.",
		Birthday:     "",
		Deathday:     "",
		PlaceOfBirth: "",
		ProfilePath:  "",
		KnownForDept: "Writing",
		Popularity:   0.8,
		Gender:       2,
		ImdbID:       "nm0090213",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           25,
		Name:         "Brigitte Helm",
		Biography:    "German actress whose dual role as Maria and her robot double in Metropolis made her a star of Weimar cinema.",
		Birthday:     "1906-03-17",
		Deathday:     "1996-06-11",
		PlaceOfBirth: "Berlin, Germany",
		ProfilePath:  "/a7mwxoeF34BCxmteoHQSB1ENth0.jpg",
		KnownForDept: "Acting",
		Popularity:   1.2,
		Gender:       1,
		ImdbID:       "nm0375609",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           26,
		Name:         "Gustav Fröhlich",
		Biography:    "German actor and director who played Freder in Metropolis.",
		Birthday:     "1902-03-21",
		Deathday:     "1987-12-22",
		PlaceOfBirth: "Hannover, Germany",
		ProfilePath:  "/bkjDaorTT3LcOeTcQF1TDpBlHwt.jpg",
		KnownForDept: "Acting",
		Popularity:   1.8,
		Gender:       2,
		ImdbID:       "nm0297054",
		AlsoKnownAs:  []string{"Gustav Froelich"},
	},
	{
		ID:           27,
		Name:         "Alfred Abel",
		Biography:    "German actor and director who played Joh Fredersen in Metropolis.",
		Birthday:     "1879-03-11",
		Deathday:     "1937-12-12",
		PlaceOfBirth: "Leipzig, Germany",
		ProfilePath:  "/dGk5r64zQZVHplTwRDZGpNkoCjc.jpg",
		KnownForDept: "Acting",
		Popularity:   1.1,
		Gender:       2,
		ImdbID:       "nm0002154",
		AlsoKnownAs:  []string{"Alfred Peter Abel"},
	},
	{
		ID:           28,
		Name:         "Rudolf Klein-Rogge",
		Biography:    "German actor known for the villains of Fritz Lang's films, including Rotwang in Metropolis and Dr. Mabuse.",
		Birthday:     "1885-11-24",
		Deathday:     "1955-05-29",
		PlaceOfBirth: "Cologne, Germany",
		ProfilePath:  "/fbP75fGfXFQlkf3Q5oHbJ4wjG1g.jpg",
		KnownForDept: "Acting",
		Popularity:   0.9,
		Gender:       2,
		ImdbID:       "nm0459030",
		AlsoKnownAs:  []string{"Friedrich Rudolf Klein-Rogge", "Friedrich Rudolf Klein"},
	},
	{
		ID:           29,
		Name:         "Thea von Harbou",
		Biography:    "German screenwriter, novelist, and director who wrote the novel and the screenplay of Metropolis.",
		Birthday:     "1888-12-19",
		Deathday:     "1954-07-01",
		PlaceOfBirth: "Tauperlitz, Germany",
		ProfilePath:  "/jQ6EF2gcodiez6PFEOaqMMF3nfF.jpg",
		KnownForDept: "Writing",
		Popularity:   1.9,
		Gender:       1,
		ImdbID:       "nm0902376",
		AlsoKnownAs:  []string{"Thea Gabriele von Harbou"},
	},
	{
		ID:           30,
		Name:         "Erich Pommer",
		Biography:    "German film producer, head of production at UFA in the 1920s, who produced Metropolis.",
		Birthday:     "1889-07-20",
		Deathday:     "1966-05-08",
		PlaceOfBirth: "Hildesheim, Germany",
		ProfilePath:  "/tDYZA5sghHNO1g4hpkRbDei2SoK.jpg",
		KnownForDept: "Production",
		Popularity:   0.5,
		Gender:       2,
		ImdbID:       "nm0690143",
		AlsoKnownAs:  []string{"Eric Pommer"},
	},
	{
		ID:           31,
		Name:         "Georges Méliès",
		Biography:    "French illusionist and filmmaker, a pioneer of special effects and narrative cinema, best known for A Trip to the Moon.",
		Birthday:     "1861-12-08",
		Deathday:     "1938-01-21",
		PlaceOfBirth: "Paris, France",
		ProfilePath:  "/acx5saf22Qj6FV5WAsacRHlZAMn.jpg",
		KnownForDept: "Directing",
		Popularity:   1.3,
		Gender:       2,
		ImdbID:       "nm0617588",
		AlsoKnownAs:  []string{"Marie Georges Jean Méliès"},
	},
	{
		ID:           32,
		Name:         "Bleuette Bernon",
		Biography:    "French singer and actress who appeared in several of Georges Méliès's early films, including A Trip to the Moon.",
		Birthday:     "1878-06-06",
		Deathday:     "1937-06-15",
		PlaceOfBirth: "Париж, Франція",
		ProfilePath:  "/u14pGZRIO0Ylsnm9tyimI6I5gbO.jpg",
		KnownForDept: "Acting",
		Popularity:   2.8,
		Gender:       1,
		ImdbID:       "nm0076933",
		AlsoKnownAs:  []string{"Léontine Ernestine Gauché"},
	},
	{
		ID:           33,
		Name:         "Victor André",
		Biography:    "French actor who appeared in Georges Méliès's films, including A Trip to the Moon.",
		Birthday:     "",
		Deathday:     "",
		PlaceOfBirth: "",
		ProfilePath:  "",
		KnownForDept: "Acting",
		Popularity:   1.1,
		Gender:       2,
		ImdbID:       "nm0029244",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           34,
		Name:         "Werner Krauss",
		Biography:    "German stage and film actor who played the title role in The Cabinet of Dr. Caligari.",
		Birthday:     "1884-06-23",
		Deathday:     "1959-10-20",
		PlaceOfBirth: "Gestungshausen, Sonnefeld, Bavaria, Germany",
		ProfilePath:  "/xlyS30qzcndmczxG5JdJWwJ1heI.jpg",
		KnownForDept: "Acting",
		Popularity:   2.3,
		Gender:       2,
		ImdbID:       "nm0470328",
		AlsoKnownAs:  []string{"Werner Johannes Krauss"},
	},
	{
		ID:           35,
		Name:         "Conrad Veidt",
		Biography:    "German actor famed as the somnambulist Cesare in Caligari, later a Hollywood star in Casablanca.",
		Birthday:     "1893-01-22",
		Deathday:     "1943-04-03",
		PlaceOfBirth: "Berlin, Germany",
		ProfilePath:  "/rmlK341dwK57BVWz1S96tpv7SSF.jpg",
		KnownForDept: "Acting",
		Popularity:   2.5,
		Gender:       2,
		ImdbID:       "nm0891998",
		AlsoKnownAs:  []string{"Hans Walter Conrad Veidt"},
	},
	{
		ID:           36,
		Name:         "Lil Dagover",
		Biography:    "German actress who played Jane in The Cabinet of Dr. Caligari and remained a leading figure of German cinema for decades.",
		Birthday:     "1887-09-29",
		Deathday:     "1980-01-23",
		PlaceOfBirth: "Madioen, Madioen, Dutch East Indies [now Madiun, East Java, Indonesia]",
		ProfilePath:  "/eNdCKI0PjnDapWEbTuZln7U2hCl.jpg",
		KnownForDept: "Acting",
		Popularity:   0.9,
		Gender:       1,
		ImdbID:       "nm0196820",
		AlsoKnownAs:  []string{"Marie Antonia Siegelinde Martha Seubert"},
	},
	{
		ID:           37,
		Name:         "Robert Wiene",
		Biography:    "German film director best known for The Cabinet of Dr. Caligari, a landmark of Expressionist cinema.",
		Birthday:     "1873-04-25",
		Deathday:     "1938-07-17",
		PlaceOfBirth: "Breslau, Silesia, Germany [now Wroclaw, Dolnoslaskie, Poland]",
		ProfilePath:  "/hljvbcgEYOHJM6FI5r6Vi2OULwg.jpg",
		KnownForDept: "Directing",
		Popularity:   0.8,
		Gender:       2,
		ImdbID:       "nm0927468",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           38,
		Name:         "Carl Mayer",
		Biography:    "Austrian screenwriter, co-author of The Cabinet of Dr. Caligari and a central writer of Weimar cinema.",
		Birthday:     "1894-11-20",
		Deathday:     "1944-07-01",
		PlaceOfBirth: "Graz, Styria, Austria-Hungary [now Austria]",
		ProfilePath:  "",
		KnownForDept: "Writing",
		Popularity:   1.2,
		Gender:       2,
		ImdbID:       "nm0562346",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           39,
		Name:         "Hans Janowitz",
		Biography:    "Czech-born writer who co-wrote The Cabinet of Dr. Caligari with Carl Mayer.",
		Birthday:     "",
		Deathday:     "",
		PlaceOfBirth: "Podebrady, Austria-Hungary",
		ProfilePath:  "",
		KnownForDept: "Writing",
		Popularity:   0.6,
		Gender:       2,
		ImdbID:       "nm0417917",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           40,
		Name:         "Audrey Hepburn",
		Biography:    "Belgian-born British actress and humanitarian, an icon of 1950s and 1960s film, who starred opposite Cary Grant in Charade.",
		Birthday:     "1929-05-04",
		Deathday:     "1993-01-20",
		PlaceOfBirth: "Ixelles, Belgium",
		ProfilePath:  "/hwPHPRz7YqmcRAlvhag5VPeoaoC.jpg",
		KnownForDept: "Acting",
		Popularity:   4.2,
		Gender:       1,
		ImdbID:       "nm0000030",
		AlsoKnownAs:  []string{"Audrey Kathleen Ruston"},
	},
	{
		ID:           41,
		Name:         "Walter Matthau",
		Biography:    "American actor known for comic roles such as The Odd Couple, and for his early turn as a villain in Charade.",
		Birthday:     "1920-10-01",
		Deathday:     "2000-07-01",
		PlaceOfBirth: "New York City, New York, USA",
		ProfilePath:  "/pm1YEQPlsNcHQHZJBgcXvu4U4vg.jpg",
		KnownForDept: "Acting",
		Popularity:   3.5,
		Gender:       2,
		ImdbID:       "nm0000527",
		AlsoKnownAs:  []string{"Walter John Matthau"},
	},
	{
		ID:           42,
		Name:         "Stanley Donen",
		Biography:    "American film director and choreographer behind Singin' in the Rain and Charade.",
		Birthday:     "1924-04-13",
		Deathday:     "2019-02-21",
		PlaceOfBirth: "Columbia, South Carolina, USA",
		ProfilePath:  "/hvRi8etQyf6Zfh7MRsRP0pBR9Om.jpg",
		KnownForDept: "Directing",
		Popularity:   2.8,
		Gender:       2,
		ImdbID:       "nm0002045",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           43,
		Name:         "Peter Stone",
		Biography:    "American screenwriter and playwright who wrote Charade and later won an Academy Award for Father Goose.",
		Birthday:     "1930-02-27",
		Deathday:     "2003-04-26",
		PlaceOfBirth: "Los Angeles, California, USA",
		ProfilePath:  "/vr7a1t0Sj2C11l2U0B2xcnvvjhK.jpg",
		KnownForDept: "Writing",
		Popularity:   2.9,
		Gender:       2,
		ImdbID:       "nm0832099",
		AlsoKnownAs:  []string{"Pierre Marton", "Peter Joshua"},
	},
	{
		ID:           44,
		Name:         "Edmond O'Brien",
		Biography:    "American actor and Academy Award winner who played the poisoned Frank Bigelow in D.O.A.",
		Birthday:     "1915-09-10",
		Deathday:     "1985-05-09",
		PlaceOfBirth: "New York City, New York, USA",
		ProfilePath:  "/wnB6xci7TzrEHwDYMvLSgY76qie.jpg",
		KnownForDept: "Acting",
		Popularity:   2.8,
		Gender:       2,
		ImdbID:       "nm0639529",
		AlsoKnownAs:  []string{"Edmund O'Brien", "Edmond Joseph O'Brien"},
	},
	{
		ID:           45,
		Name:         "Pamela Britton",
		Biography:    "American actress of film and television who played Paula Gibson in D.O.A.",
		Birthday:     "1923-03-19",
		Deathday:     "1974-06-17",
		PlaceOfBirth: "Milwaukee, Wisconsin, USA",
		ProfilePath:  "/dRDBaqZRfyKFSiBf5ZgbM6sVFuY.jpg",
		KnownForDept: "Acting",
		Popularity:   0.9,
		Gender:       1,
		ImdbID:       "nm0110219",
		AlsoKnownAs:  []string{"Armilda Jane Owens"},
	},
	{
		ID:           46,
		Name:         "Luther Adler",
		Biography:    "American actor of the Group Theatre and film, cast as the gangster Majak in D.O.A.",
		Birthday:     "1903-05-04",
		Deathday:     "1984-12-08",
		PlaceOfBirth: "New York City, New York, USA",
		ProfilePath:  "/kpN6ObaFLQUzBe7STFIPnY0UB7i.jpg",
		KnownForDept: "Acting",
		Popularity:   2.0,
		Gender:       2,
		ImdbID:       "nm0012204",
		AlsoKnownAs:  []string{"Lutha Adler"},
	},
	{
		ID:           47,
		Name:         "Rudolph Maté",
		Biography:    "Polish-born cinematographer turned director, celebrated for his camerawork on The Passion of Joan of Arc before directing D.O.A.",
		Birthday:     "1898-01-21",
		Deathday:     "1964-10-27",
		PlaceOfBirth: "Krakau, Galicia, Austria-Hungary [now Kraków, Malopolskie, Poland]",
		ProfilePath:  "/pq0x1cUNdapjIvmnipOiWQxABb1.jpg",
		KnownForDept: "Directing",
		Popularity:   1.4,
		Gender:       2,
		ImdbID:       "nm0005789",
		AlsoKnownAs:  []string{"Rudolphe Mate", "Rudy Maté"},
	},
	{
		ID:           48,
		Name:         "Russell Rouse",
		Biography:    "American screenwriter and director who co-wrote D.O.A. with Clarence Greene.",
		Birthday:     "1913-11-20",
		Deathday:     "1987-10-02",
		PlaceOfBirth: "New York City, New York, USA",
		ProfilePath:  "",
		KnownForDept: "Writing",
		Popularity:   1.2,
		Gender:       2,
		ImdbID:       "nm0745866",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           49,
		Name:         "Clarence Greene",
		Biography:    "American screenwriter and producer, a longtime collaborator of Russell Rouse on films including D.O.A.",
		Birthday:     "1913-08-10",
		Deathday:     "1995-06-17",
		PlaceOfBirth: "New York City, New York, USA",
		ProfilePath:  "",
		KnownForDept: "Writing",
		Popularity:   0.9,
		Gender:       2,
		ImdbID:       "nm0338707",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           50,
		Name:         "Lon Chaney",
		Biography:    "American actor known as the Man of a Thousand Faces for his transformative makeup work, including the Phantom of the Opera.",
		Birthday:     "1883-03-31",
		Deathday:     "1930-08-26",
		PlaceOfBirth: "Colorado Springs, Colorado, USA",
		ProfilePath:  "/m1icBooBEqFNp24Puu7qXn2Sarr.jpg",
		KnownForDept: "Acting",
		Popularity:   1.4,
		Gender:       2,
		ImdbID:       "nm0151606",
		AlsoKnownAs:  []string{"Leonidas Frank Chaney", "Man of a Thousand Faces"},
	},
	{
		ID:           51,
		Name:         "Mary Philbin",
		Biography:    "American silent-film actress who played Christine Daaé in The Phantom of the Opera.",
		Birthday:     "1902-07-16",
		Deathday:     "1993-05-07",
		PlaceOfBirth: "Chicago, Illinois, USA",
		ProfilePath:  "/grqaQFQSBIl26uv2VrmdneaLpJ9.jpg",
		KnownForDept: "Acting",
		Popularity:   1.1,
		Gender:       1,
		ImdbID:       "nm0679907",
		AlsoKnownAs:  []string{"Mary Loretta Philbin", "Mary L. Philbin"},
	},
	{
		ID:           52,
		Name:         "Norman Kerry",
		Biography:    "American silent-film actor who played Raoul de Chagny in The Phantom of the Opera.",
		Birthday:     "1894-06-15",
		Deathday:     "1956-01-12",
		PlaceOfBirth: "Rochester, New York, USA",
		ProfilePath:  "/luQTt1kDR73AclpZeFeQPzPuhjc.jpg",
		KnownForDept: "Acting",
		Popularity:   0.7,
		Gender:       2,
		ImdbID:       "nm0449908",
		AlsoKnownAs:  []string{"Norman Hussey Kaiser", "Norman Kaiser"},
	},
	{
		ID:           53,
		Name:         "Rupert Julian",
		Biography:    "New Zealand-born actor and director credited with directing The Phantom of the Opera.",
		Birthday:     "1879-01-23",
		Deathday:     "1943-12-27",
		PlaceOfBirth: "Whangaroa, New Zealand",
		ProfilePath:  "/9dWgryyjsLz1dw9cxMNvuB5piEh.jpg",
		KnownForDept: "Directing",
		Popularity:   1.6,
		Gender:       2,
		ImdbID:       "nm0432216",
		AlsoKnownAs:  []string{"Thomas Percival Hayes"},
	},
	{
		ID:           54,
		Name:         "Gaston Leroux",
		Biography:    "French journalist and novelist who wrote The Phantom of the Opera.",
		Birthday:     "1868-05-06",
		Deathday:     "1927-04-15",
		PlaceOfBirth: "Paris, France",
		ProfilePath:  "/r4NGVNWTDXvJQVeOlAXX6mgkI79.jpg",
		KnownForDept: "Writing",
		Popularity:   1.4,
		Gender:       2,
		ImdbID:       "nm0503693",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           55,
		Name:         "Carl Laemmle",
		Biography:    "German-born founder of Universal Pictures who produced its silent-era productions, including The Phantom of the Opera.",
		Birthday:     "1867-01-17",
		Deathday:     "1939-09-24",
		PlaceOfBirth: "Laupheim - Baden-Württemberg - Germany",
		ProfilePath:  "/4UBMh6AJxS5gUJVlkIgswDc3rlJ.jpg",
		KnownForDept: "Production",
		Popularity:   0.8,
		Gender:       2,
		ImdbID:       "nm0480674",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           56,
		Name:         "Jonathan Haze",
		Biography:    "American actor, a regular in Roger Corman's early films, who played Seymour in The Little Shop of Horrors.",
		Birthday:     "1929-04-01",
		Deathday:     "",
		PlaceOfBirth: "Pittsburgh, Pennsylvania, USA",
		ProfilePath:  "/lFKaVuZW3gHF1Qw4CZQS5ZPr926.jpg",
		KnownForDept: "Acting",
		Popularity:   1.0,
		Gender:       2,
		ImdbID:       "nm0371918",
		AlsoKnownAs:  []string{"Jack Schachter", "Jack Hayes"},
	},
	{
		ID:           57,
		Name:         "Jackie Joseph",
		Biography:    "American actress who played Audrey in the original The Little Shop of Horrors.",
		Birthday:     "1934-11-07",
		Deathday:     "",
		PlaceOfBirth: "Los Angeles, California, USA",
		ProfilePath:  "/2DkqtrIJs8d4GycqVyKjoPfNnsV.jpg",
		KnownForDept: "Acting",
		Popularity:   2.7,
		Gender:       1,
		ImdbID:       "nm0430604",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           58,
		Name:         "Jack Nicholson",
		Biography:    "American actor with three Academy Awards; one of his earliest roles was the masochistic dental patient in The Little Shop of Horrors.",
		Birthday:     "1937-04-22",
		Deathday:     "",
		PlaceOfBirth: "Manhattan, New York, USA",
		ProfilePath:  "/hBHcQIEa6P48HQAlLZkh0eKSSkG.jpg",
		KnownForDept: "Acting",
		Popularity:   6.7,
		Gender:       2,
		ImdbID:       "nm0000197",
		AlsoKnownAs:  []string{"John Joseph Nicholson", "Jack Joseph Nicholson"},
	},
	{
		ID:           59,
		Name:         "Roger Corman",
		Biography:    "American producer and director, the prolific king of low-budget independent film, who shot The Little Shop of Horrors in two days.",
		Birthday:     "1926-04-05",
		Deathday:     "2024-05-09",
		PlaceOfBirth: "Detroit, Michigan, USA",
		ProfilePath:  "/m0ApZMol42l8vLV8MLpUSCpyA6n.jpg",
		KnownForDept: "Directing",
		Popularity:   3.1,
		Gender:       2,
		ImdbID:       "nm0000339",
		AlsoKnownAs:  []string{"Roger William Corman", "The Pope of Pop Cinema"},
	},
	{
		ID:           60,
		Name:         "Charles B. Griffith",
		Biography:    "American screenwriter and frequent Roger Corman collaborator who wrote The Little Shop of Horrors.",
		Birthday:     "1930-09-23",
		Deathday:     "2007-09-28",
		PlaceOfBirth: "Chicago, Illinois, USA",
		ProfilePath:  "/tLDw8ioMJysFcl5jgSW2u0u95yQ.jpg",
		KnownForDept: "Writing",
		Popularity:   1.5,
		Gender:       2,
		ImdbID:       "nm0341458",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           61,
		Name:         "Gregory Walcott",
		Biography:    "American actor with a long career in westerns and television who played pilot Jeff Trent in Plan 9 from Outer Space.",
		Birthday:     "1928-01-13",
		Deathday:     "2015-03-20",
		PlaceOfBirth: "Wendell, North Carolina, USA",
		ProfilePath:  "/tOKACaAYyPjNcVbHGIKhZwJ4wB8.jpg",
		KnownForDept: "Acting",
		Popularity:   3.1,
		Gender:       2,
		ImdbID:       "nm0906966",
		AlsoKnownAs:  []string{"Bernard Wasdon Mattox"},
	},
	{
		ID:           62,
		Name:         "Bela Lugosi",
		Biography:    "Hungarian-American actor immortalized as Dracula; footage shot shortly before his death was used in Plan 9 from Outer Space.",
		Birthday:     "1882-10-17",
		Deathday:     "1956-08-16",
		PlaceOfBirth: "Lugos, Kingdom of Hungary, Austria-Hungary [now Lugoj, Timis County, Romania]",
		ProfilePath:  "/fwimu7WKcaJXIjaDwYQg42GxUxa.jpg",
		KnownForDept: "Acting",
		Popularity:   1.8,
		Gender:       2,
		ImdbID:       "nm0000509",
		AlsoKnownAs:  []string{"Béla Ferenc Dezsõ Blaskó", "Olt Arisztid"},
	},
	{
		ID:           63,
		Name:         "Maila Nurmi",
		Biography:    "Finnish-American actress and television horror host who created the character Vampira and played the Vampire Girl in Plan 9 from Outer Space.",
		Birthday:     "1922-12-11",
		Deathday:     "2008-01-10",
		PlaceOfBirth: "Gloucester, Massachusetts, USA",
		ProfilePath:  "/gjbZHnsVmltAPah6n8zf3Xuy2J5.jpg",
		KnownForDept: "Acting",
		Popularity:   0.7,
		Gender:       1,
		ImdbID:       "nm0885533",
		AlsoKnownAs:  []string{"Vampira"},
	},
	{
		ID:           64,
		Name:         "Ed Wood",
		Biography:    "American filmmaker whose low-budget genre films, including Plan 9 from Outer Space, earned him a devoted cult following.",
		Birthday:     "1924-10-10",
		Deathday:     "1978-12-10",
		PlaceOfBirth: "Poughkeepsie, New York, USA",
		ProfilePath:  "/lpJ6li6nsuMW2ytAS65o20tZHma.jpg",
		KnownForDept: "Directing",
		Popularity:   1.5,
		Gender:       2,
		ImdbID:       "nm0000248",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           65,
		Name:         "Vincent Price",
		Biography:    "American actor whose distinctive voice and presence made him a horror icon; he played the last survivor in The Last Man on Earth.",
		Birthday:     "1911-05-27",
		Deathday:     "1993-10-25",
		PlaceOfBirth: "Saint Louis, Missouri, USA",
		ProfilePath:  "/7JIv7U5kwveryP7hrPYgHlKea4d.jpg",
		KnownForDept: "Acting",
		Popularity:   3.6,
		Gender:       2,
		ImdbID:       "nm0001637",
		AlsoKnownAs:  []string{"Vincent Leonard Price Jr.", "The King of the Grand Guignol"},
	},
	{
		ID:           66,
		Name:         "Franca Bettoia",
		Biography:    "Italian actress who played Ruth Collins in The Last Man on Earth.",
		Birthday:     "1936-05-14",
		Deathday:     "",
		PlaceOfBirth: "Roma, Lazio, Italy",
		ProfilePath:  "/uxqFYe1lEHwB8AGABn5pEBJMllx.jpg",
		KnownForDept: "Acting",
		Popularity:   1.3,
		Gender:       1,
		ImdbID:       "nm0079399",
		AlsoKnownAs:  []string{"Franca Bettoja"},
	},
	{
		ID:           67,
		Name:         "Emma Danieli",
		Biography:    "Italian actress and television presenter who played Virginia Morgan in The Last Man on Earth.",
		Birthday:     "1936-10-14",
		Deathday:     "1998-06-21",
		PlaceOfBirth: "Buscoldo, Curtatone, Lombardy, Italy",
		ProfilePath:  "/aazKjmnrmj2hdjzXviv9SOD7deX.jpg",
		KnownForDept: "Acting",
		Popularity:   0.7,
		Gender:       1,
		ImdbID:       "nm0199618",
		AlsoKnownAs:  []string{"Emma Fretta", "Emma Danielli"},
	},
	{
		ID:           68,
		Name:         "Ubaldo Ragona",
		Biography:    "Italian director who co-directed The Last Man on Earth.",
		Birthday:     "1916-12-01",
		Deathday:     "1987-08-15",
		PlaceOfBirth: " Catania, Sicily, Italy",
		ProfilePath:  "",
		KnownForDept: "Directing",
		Popularity:   0.4,
		Gender:       2,
		ImdbID:       "nm0706575",
		AlsoKnownAs:  []string{"Edward Dein", "Ubaldo B. Ragona"},
	},
	{
		ID:           69,
		Name:         "Sidney Salkow",
		Biography:    "American film and television director who co-directed The Last Man on Earth.",
		Birthday:     "1909-06-16",
		Deathday:     "2000-10-18",
		PlaceOfBirth: "New York City, New York, USA",
		ProfilePath:  "/gXA7M6vZ4mAmMCSyu1xuaIWk83g.jpg",
		KnownForDept: "Directing",
		Popularity:   1.0,
		Gender:       2,
		ImdbID:       "nm0758508",
		AlsoKnownAs:  []string{"Sid Salkow"},
	},
	{
		ID:           70,
		Name:         "Richard Matheson",
		Biography:    "American author and screenwriter whose novel I Am Legend was adapted as The Last Man on Earth.",
		Birthday:     "1926-02-20",
		Deathday:     "2013-06-23",
		PlaceOfBirth: "Allendale, New Jersey, USA",
		ProfilePath:  "/fTsTj0EMqH5GfVN0Kj252jsYZnB.jpg",
		KnownForDept: "Writing",
		Popularity:   3.0,
		Gender:       2,
		ImdbID:       "nm0558577",
		AlsoKnownAs:  []string{"Richard Burton Matheson", "Logan Swanson"},
	},
	{
		ID:           71,
		Name:         "Frank Sinatra",
		Biography:    "American singer and actor, one of the century's best-selling artists, who played the would-be assassin John Baron in Suddenly.",
		Birthday:     "1915-12-12",
		Deathday:     "1998-05-14",
		PlaceOfBirth: "Hoboken, New Jersey, USA",
		ProfilePath:  "/dafKPsivu50RdChBSrgGmMRenYt.jpg",
		KnownForDept: "Acting",
		Popularity:   2.5,
		Gender:       2,
		ImdbID:       "nm0000069",
		AlsoKnownAs:  []string{"Francis Albert Sinatra"},
	},
	{
		ID:           72,
		Name:         "Sterling Hayden",
		Biography:    "American actor and author known for film noir, The Killing, and Dr. Strangelove; he played Sheriff Tod Shaw in Suddenly.",
		Birthday:     "1916-03-26",
		Deathday:     "1986-05-23",
		PlaceOfBirth: "Upper Montclair, New Jersey, USA",
		ProfilePath:  "/dCTe6BsGSp9QTcva2Pz4wbxxYMY.jpg",
		KnownForDept: "Acting",
		Popularity:   3.5,
		Gender:       2,
		ImdbID:       "nm0001330",
		AlsoKnownAs:  []string{"Sterling Relyea Walter", "Sterling Walter Hayden"},
	},
	{
		ID:           73,
		Name:         "James Gleason",
		Biography:    "American actor, playwright, and screenwriter, a familiar character actor who played Pop Benson in Suddenly.",
		Birthday:     "1882-05-23",
		Deathday:     "1959-04-12",
		PlaceOfBirth: "New York City, New York, USA",
		ProfilePath:  "/nIWAiRVuVbEfD8iSWymhOSJlWUm.jpg",
		KnownForDept: "Acting",
		Popularity:   2.2,
		Gender:       2,
		ImdbID:       "nm0322299",
		AlsoKnownAs:  []string{"James Austin Gleason", "Jimmy Gleason"},
	},
	{
		ID:           74,
		Name:         "Lewis Allen",
		Biography:    "English-born director of The Uninvited and Suddenly who later worked extensively in American television.",
		Birthday:     "1905-12-25",
		Deathday:     "2000-05-03",
		PlaceOfBirth: "Oakengates, Shropshire, England, UK",
		ProfilePath:  "/7Gg3zxSv8ykJpEGLyIfZDRyMn9r.jpg",
		KnownForDept: "Directing",
		Popularity:   1.5,
		Gender:       2,
		ImdbID:       "nm0020765",
		AlsoKnownAs:  []string{"Abel Meeropol"},
	},
	{
		ID:           75,
		Name:         "Richard Sale",
		Biography:    "American writer and director of pulp fiction and film who wrote the screenplay for Suddenly.",
		Birthday:     "1911-12-17",
		Deathday:     "1993-03-04",
		PlaceOfBirth: " New York City, New York, USA",
		ProfilePath:  "",
		KnownForDept: "Writing",
		Popularity:   1.9,
		Gender:       2,
		ImdbID:       "nm0757940",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           76,
		Name:         "Robert Bassler",
		Biography:    "American film producer who produced Suddenly.",
		Birthday:     "1903-09-26",
		Deathday:     "1975-11-08",
		PlaceOfBirth: "Washington, District of Columbia, USA",
		ProfilePath:  "",
		KnownForDept: "Production",
		Popularity:   0.4,
		Gender:       2,
		ImdbID:       "nm0060317",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           77,
		Name:         "Tom Neal",
		Biography:    "American actor and boxer best remembered as the doomed hitchhiker Al Roberts in Detour.",
		Birthday:     "1914-01-28",
		Deathday:     "1972-08-07",
		PlaceOfBirth: "Evanston, Illinois, USA",
		ProfilePath:  "/m0h1k9LV7I86f4D2FRMujDcI76h.jpg",
		KnownForDept: "Acting",
		Popularity:   1.1,
		Gender:       2,
		ImdbID:       "nm0623684",
		AlsoKnownAs:  []string{"Thomas Carroll Neal Jr.", "Thomas Neal"},
	},
	{
		ID:           78,
		Name:         "Ann Savage",
		Biography:    "American actress whose ferocious performance as Vera in Detour is among film noir's most famous.",
		Birthday:     "1921-02-19",
		Deathday:     "2008-12-25",
		PlaceOfBirth: "Columbia, South Carolina, USA",
		ProfilePath:  "/54yRVZqtboMxdRvkIvhfO1xvgu9.jpg",
		KnownForDept: "Acting",
		Popularity:   2.2,
		Gender:       1,
		ImdbID:       "nm0767243",
		AlsoKnownAs:  []string{"Berniece Maxine Lyon"},
	},
	{
		ID:           79,
		Name:         "Claudia Drake",
		Biography:    "American actress and singer who played Sue Harvey in Detour.",
		Birthday:     "1918-01-30",
		Deathday:     "1997-10-19",
		PlaceOfBirth: " Los Angeles, California, USA",
		ProfilePath:  "/5kJwLxMktqPfDYQ5X3E2ti9kOMI.jpg",
		KnownForDept: "Acting",
		Popularity:   0.7,
		Gender:       1,
		ImdbID:       "nm0236873",
		AlsoKnownAs:  []string{"Olga Gloria Fishbine"},
	},
	{
		ID:           80,
		Name:         "Edgar G. Ulmer",
		Biography:    "Austrian-American director known for turning tiny budgets into striking films, most famously Detour.",
		Birthday:     "1904-09-17",
		Deathday:     "1972-09-30",
		PlaceOfBirth: "Olmütz, Moravia, Austria-Hungary [now Olomouc, Czech Republic]",
		ProfilePath:  "/uH5SR17ZJwe4y9K1CtkfQerIcCu.jpg",
		KnownForDept: "Directing",
		Popularity:   1.3,
		Gender:       2,
		ImdbID:       "nm0880618",
		AlsoKnownAs:  []string{"John Warner", "Edgar George Ulmer"},
	},
	{
		ID:           81,
		Name:         "Martin Goldsmith",
		Biography:    "American novelist and screenwriter who adapted his own novel into Detour.",
		Birthday:     "1913-11-06",
		Deathday:     "1994-05-24",
		PlaceOfBirth: "New York City, New York, USA",
		ProfilePath:  "",
		KnownForDept: "Writing",
		Popularity:   0.8,
		Gender:       2,
		ImdbID:       "nm0326107",
		AlsoKnownAs:  []string{"Martin M. Goldsmith"},
	},
	{
		ID:           82,
		Name:         "Leon Fromkess",
		Biography:    "American film producer and executive at Producers Releasing Corporation who produced Detour.",
		Birthday:     "1901-11-23",
		Deathday:     "1977-03-11",
		PlaceOfBirth: "New York, New York, USA",
		ProfilePath:  "",
		KnownForDept: "Production",
		Popularity:   0.5,
		Gender:       2,
		ImdbID:       "nm0003199",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           83,
		Name:         "Robert Donat",
		Biography:    "English actor and Academy Award winner who played Richard Hannay in Hitchcock's The 39 Steps.",
		Birthday:     "1905-03-18",
		Deathday:     "1958-06-09",
		PlaceOfBirth: "Withington, Manchester, England, UK",
		ProfilePath:  "/zIgfKqnrmvsFXnhDpm1S90lHprD.jpg",
		KnownForDept: "Acting",
		Popularity:   1.2,
		Gender:       2,
		ImdbID:       "nm0232196",
		AlsoKnownAs:  []string{"Friedrich Robert Donat", "Friedrich Robert Donath"},
	},
	{
		ID:           84,
		Name:         "Madeleine Carroll",
		Biography:    "English actress, one of the first Hitchcock blondes, who starred as Pamela in The 39 Steps.",
		Birthday:     "1906-02-26",
		Deathday:     "1987-10-02",
		PlaceOfBirth: "West Bromwich, England, UK",
		ProfilePath:  "/7bGv0tsoCDbxZn3QCPVanO2tJlC.jpg",
		KnownForDept: "Acting",
		Popularity:   2.0,
		Gender:       1,
		ImdbID:       "nm0140914",
		AlsoKnownAs:  []string{"Edith Madeleine Carroll", "The Queen of British Cinema"},
	},
	{
		ID:           85,
		Name:         "Lucie Mannheim",
		Biography:    "German-born actress who played the spy Annabella Smith in The 39 Steps.",
		Birthday:     "1899-04-30",
		Deathday:     "1976-07-18",
		PlaceOfBirth: "Berlin, Germany",
		ProfilePath:  "/kZopL96zPk9eHADcDPUMwh5cFu5.jpg",
		KnownForDept: "Acting",
		Popularity:   1.3,
		Gender:       1,
		ImdbID:       "nm0543169",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           86,
		Name:         "Alfred Hitchcock",
		Biography:    "English filmmaker known as the Master of Suspense, whose British period includes The 39 Steps.",
		Birthday:     "1899-08-13",
		Deathday:     "1980-04-29",
		PlaceOfBirth: "Leytonstone, London, England, UK",
		ProfilePath:  "/108fiNM6poRieMg7RIqLJRxdAwG.jpg",
		KnownForDept: "Directing",
		Popularity:   6.3,
		Gender:       2,
		ImdbID:       "nm0000033",
		AlsoKnownAs:  []string{"The Master of Suspense", "Sir Alfred Hitchcock"},
	},
	{
		ID:           87,
		Name:         "Charles Bennett",
		Biography:    "English playwright and screenwriter, a key collaborator of Alfred Hitchcock in the 1930s.",
		Birthday:     "1899-08-02",
		Deathday:     "1995-06-15",
		PlaceOfBirth: "Shoreham-by-Sea, England",
		ProfilePath:  "/32S9hq6NXKjchDb31YbM7YJVJlr.jpg",
		KnownForDept: "Writing",
		Popularity:   2.1,
		Gender:       2,
		ImdbID:       "nm0071657",
		AlsoKnownAs:  []string{"John H. Kneubuhl"},
	},
	{
		ID:           88,
		Name:         "John Buchan",
		Biography:    "Scottish novelist and politician whose 1915 novel The Thirty-Nine Steps inspired Hitchcock's film.",
		Birthday:     "1875-08-26",
		Deathday:     "1940-02-11",
		PlaceOfBirth: "Perth, Perthshire, Scotland, UK",
		ProfilePath:  "",
		KnownForDept: "Writing",
		Popularity:   0.7,
		Gender:       2,
		ImdbID:       "nm0117955",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           89,
		Name:         "Michael Balcon",
		Biography:    "English film producer who ran Gaumont-British and later Ealing Studios, producing Hitchcock's The 39 Steps.",
		Birthday:     "1896-05-19",
		Deathday:     "1977-10-17",
		PlaceOfBirth: "Birmingham, England, UK",
		ProfilePath:  "/7oXyC5zXm21XKtRioM4s3TbWahG.jpg",
		KnownForDept: "Production",
		Popularity:   0.7,
		Gender:       2,
		ImdbID:       "nm0049608",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           90,
		Name:         "John Wayne",
		Biography:    "American actor and one of the most popular stars of the western, who played the cattle baron G.W. McLintock.",
		Birthday:     "1907-05-26",
		Deathday:     "1979-06-11",
		PlaceOfBirth: "Winterset, Iowa, USA ",
		ProfilePath:  "/4VmiGmCwSnratHtYmT2AyXrdQ64.jpg",
		KnownForDept: "Acting",
		Popularity:   4.0,
		Gender:       2,
		ImdbID:       "nm0000078",
		AlsoKnownAs:  []string{"Duke", "The Duke"},
	},
	{
		ID:           91,
		Name:         "Maureen O'Hara",
		Biography:    "Irish-American actress, frequently paired with John Wayne, who played Katherine McLintock.",
		Birthday:     "1920-08-17",
		Deathday:     "2015-10-24",
		PlaceOfBirth: "Ranelagh, County Dublin, Ireland",
		ProfilePath:  "/yGNh18kBF7afOdjTcEP2zFCxzCH.jpg",
		KnownForDept: "Acting",
		Popularity:   3.1,
		Gender:       1,
		ImdbID:       "nm0000058",
		AlsoKnownAs:  []string{"Maureen FitzSimons"},
	},
	{
		ID:           92,
		Name:         "Patrick Wayne",
		Biography:    "American actor, the son of John Wayne, who played Devlin Warren in McLintock!",
		Birthday:     "1939-07-15",
		Deathday:     "",
		PlaceOfBirth: "Los Angeles, California, USA",
		ProfilePath:  "/u0EjouQWSjqr5npkGW9EXLNNAnC.jpg",
		KnownForDept: "Acting",
		Popularity:   2.1,
		Gender:       2,
		ImdbID:       "nm0915618",
		AlsoKnownAs:  []string{"Pat Wayne"},
	},
	{
		ID:           93,
		Name:         "Andrew V. McLaglen",
		Biography:    "British-American director of westerns and adventure films, including McLintock!",
		Birthday:     "1920-07-28",
		Deathday:     "2014-08-30",
		PlaceOfBirth: "London, England, UK",
		ProfilePath:  "/4Lxdxg5akHhsHoZToFe62L8RM9B.jpg",
		KnownForDept: "Directing",
		Popularity:   1.3,
		Gender:       2,
		ImdbID:       "nm0572132",
		AlsoKnownAs:  []string{"Andrew Victor McLaglen", "Andrew McLaglen"},
	},
	{
		ID:           94,
		Name:         "James Edward Grant",
		Biography:    "American screenwriter and longtime John Wayne collaborator who wrote McLintock!",
		Birthday:     "1905-07-02",
		Deathday:     "1966-02-19",
		PlaceOfBirth: "Chicago, Illinois, USA",
		ProfilePath:  "/2fDEOkZZZLgCelJGljLR18M2IGb.jpg",
		KnownForDept: "Writing",
		Popularity:   1.0,
		Gender:       2,
		ImdbID:       "nm0335455",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           95,
		Name:         "Michael Wayne",
		Biography:    "American film producer, John Wayne's eldest son, who ran Batjac Productions and produced McLintock!",
		Birthday:     "1934-01-23",
		Deathday:     "2003-04-02",
		PlaceOfBirth: "",
		ProfilePath:  "",
		KnownForDept: "Production",
		Popularity:   0.6,
		Gender:       2,
		ImdbID:       "nm0915609",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           96,
		Name:         "Candace Hilligoss",
		Biography:    "American actress whose lead role as Mary Henry in Carnival of Souls became a cult touchstone.",
		Birthday:     "1935-08-14",
		Deathday:     "",
		PlaceOfBirth: "Huron, South Dakota, USA",
		ProfilePath:  "/2snLWDrBcNfkOIf0f8TlBG404eV.jpg",
		KnownForDept: "Acting",
		Popularity:   0.5,
		Gender:       1,
		ImdbID:       "nm0385010",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           97,
		Name:         "Frances Feist",
		Biography:    "American actress who played Mrs. Thomas, the landlady, in Carnival of Souls.",
		Birthday:     "1903-05-13",
		Deathday:     "1981-03-11",
		PlaceOfBirth: "",
		ProfilePath:  "",
		KnownForDept: "Acting",
		Popularity:   0.4,
		Gender:       1,
		ImdbID:       "nm0270766",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           98,
		Name:         "Sidney Berger",
		Biography:    "American actor and theatre professor who played John Linden in Carnival of Souls.",
		Birthday:     "1935-07-25",
		Deathday:     "2013-02-15",
		PlaceOfBirth: "New York City, New York, USA",
		ProfilePath:  "",
		KnownForDept: "Acting",
		Popularity:   0.5,
		Gender:       2,
		ImdbID:       "nm0074367",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           99,
		Name:         "Herk Harvey",
		Biography:    "American director of industrial and educational films whose one feature, Carnival of Souls, became a cult classic.",
		Birthday:     "1924-06-03",
		Deathday:     "1996-04-03",
		PlaceOfBirth: "Fort Collins, Colorado, USA",
		ProfilePath:  "/3QxMAsXAfmxJYDFq1PwlQnk90ce.jpg",
		KnownForDept: "Directing",
		Popularity:   0.6,
		Gender:       2,
		ImdbID:       "nm0367547",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           100,
		Name:         "John Clifford",
		Biography:    "American writer who scripted Carnival of Souls for his Centron colleague Herk Harvey.",
		Birthday:     "1918-10-19",
		Deathday:     "2010-03-02",
		PlaceOfBirth: "Springfield, Illinois, USA",
		ProfilePath:  "",
		KnownForDept: "Writing",
		Popularity:   0.5,
		Gender:       2,
		ImdbID:       "nm0166647",
		AlsoKnownAs:  []string{},
	},
	// Invented people behind the fictional shows (no TMDB counterpart).
	{
		ID:           101,
		Name:         "Helena Ashworth",
		Biography:    "Creator and head writer of Sherlock Holmes Adventures.",
		Birthday:     "",
		Deathday:     "",
		PlaceOfBirth: "",
		ProfilePath:  "",
		KnownForDept: "Writing",
		Popularity:   3.2,
		Gender:       1,
		ImdbID:       "",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           102,
		Name:         "Edmund Hargreave",
		Biography:    "Stage-trained actor who plays Sherlock Holmes in Sherlock Holmes Adventures.",
		Birthday:     "",
		Deathday:     "",
		PlaceOfBirth: "",
		ProfilePath:  "",
		KnownForDept: "Acting",
		Popularity:   3.6,
		Gender:       2,
		ImdbID:       "",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           103,
		Name:         "Tobias Renwick",
		Biography:    "Actor who plays Dr. John Watson in Sherlock Holmes Adventures.",
		Birthday:     "",
		Deathday:     "",
		PlaceOfBirth: "",
		ProfilePath:  "",
		KnownForDept: "Acting",
		Popularity:   4.0,
		Gender:       2,
		ImdbID:       "",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           104,
		Name:         "Callum Reyes",
		Biography:    "Television director; lead director on Sherlock Holmes Adventures.",
		Birthday:     "",
		Deathday:     "",
		PlaceOfBirth: "",
		ProfilePath:  "",
		KnownForDept: "Directing",
		Popularity:   4.4,
		Gender:       2,
		ImdbID:       "",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           105,
		Name:         "Marta Oyelaran",
		Biography:    "Creator of Classic Science Theater and its riffing format.",
		Birthday:     "",
		Deathday:     "",
		PlaceOfBirth: "",
		ProfilePath:  "",
		KnownForDept: "Writing",
		Popularity:   2.0,
		Gender:       1,
		ImdbID:       "",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           106,
		Name:         "Jonah Kestrel",
		Biography:    "Comedian who hosts Classic Science Theater.",
		Birthday:     "",
		Deathday:     "",
		PlaceOfBirth: "",
		ProfilePath:  "",
		KnownForDept: "Acting",
		Popularity:   2.4,
		Gender:       2,
		ImdbID:       "",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           107,
		Name:         "Wren Okafor",
		Biography:    "Voice actor behind Gizmo, the robot co-host of Classic Science Theater.",
		Birthday:     "",
		Deathday:     "",
		PlaceOfBirth: "",
		ProfilePath:  "",
		KnownForDept: "Acting",
		Popularity:   2.8,
		Gender:       1,
		ImdbID:       "",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           108,
		Name:         "Felix Brandt",
		Biography:    "Director of Classic Science Theater.",
		Birthday:     "",
		Deathday:     "",
		PlaceOfBirth: "",
		ProfilePath:  "",
		KnownForDept: "Directing",
		Popularity:   3.2,
		Gender:       2,
		ImdbID:       "",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           109,
		Name:         "Lydia Marchetti",
		Biography:    "Creator and showrunner of The Public Domain Players.",
		Birthday:     "",
		Deathday:     "",
		PlaceOfBirth: "",
		ProfilePath:  "",
		KnownForDept: "Writing",
		Popularity:   3.6,
		Gender:       1,
		ImdbID:       "",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           110,
		Name:         "Ines Calloway",
		Biography:    "Stage actress and ensemble lead of The Public Domain Players.",
		Birthday:     "",
		Deathday:     "",
		PlaceOfBirth: "",
		ProfilePath:  "",
		KnownForDept: "Acting",
		Popularity:   4.0,
		Gender:       1,
		ImdbID:       "",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           111,
		Name:         "Rafael Duarte",
		Biography:    "Actor and ensemble member of The Public Domain Players.",
		Birthday:     "",
		Deathday:     "",
		PlaceOfBirth: "",
		ProfilePath:  "",
		KnownForDept: "Acting",
		Popularity:   4.4,
		Gender:       2,
		ImdbID:       "",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           112,
		Name:         "Owen Fairweather",
		Biography:    "Theatre and television director of The Public Domain Players.",
		Birthday:     "",
		Deathday:     "",
		PlaceOfBirth: "",
		ProfilePath:  "",
		KnownForDept: "Directing",
		Popularity:   2.0,
		Gender:       2,
		ImdbID:       "",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           113,
		Name:         "Samuel Achebe",
		Biography:    "Film historian who created Vintage Comedy Hour and appears on it.",
		Birthday:     "",
		Deathday:     "",
		PlaceOfBirth: "",
		ProfilePath:  "",
		KnownForDept: "Writing",
		Popularity:   2.4,
		Gender:       2,
		ImdbID:       "",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           114,
		Name:         "Beatrix Lindqvist",
		Biography:    "Presenter and host of Vintage Comedy Hour.",
		Birthday:     "",
		Deathday:     "",
		PlaceOfBirth: "",
		ProfilePath:  "",
		KnownForDept: "Acting",
		Popularity:   2.8,
		Gender:       1,
		ImdbID:       "",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           115,
		Name:         "Nora Halvorsen",
		Biography:    "Documentary director of Vintage Comedy Hour.",
		Birthday:     "",
		Deathday:     "",
		PlaceOfBirth: "",
		ProfilePath:  "",
		KnownForDept: "Directing",
		Popularity:   3.2,
		Gender:       1,
		ImdbID:       "",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           116,
		Name:         "Dev Raghunathan",
		Biography:    "Creator of the anthology series Tales from the Public Domain.",
		Birthday:     "",
		Deathday:     "",
		PlaceOfBirth: "",
		ProfilePath:  "",
		KnownForDept: "Writing",
		Popularity:   3.6,
		Gender:       2,
		ImdbID:       "",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           117,
		Name:         "Amara Sotelo",
		Biography:    "Actress in the rotating company of Tales from the Public Domain.",
		Birthday:     "",
		Deathday:     "",
		PlaceOfBirth: "",
		ProfilePath:  "",
		KnownForDept: "Acting",
		Popularity:   4.0,
		Gender:       1,
		ImdbID:       "",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           118,
		Name:         "Kit Bramwell",
		Biography:    "Actor in the rotating company of Tales from the Public Domain.",
		Birthday:     "",
		Deathday:     "",
		PlaceOfBirth: "",
		ProfilePath:  "",
		KnownForDept: "Acting",
		Popularity:   4.4,
		Gender:       2,
		ImdbID:       "",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           119,
		Name:         "Ingrid Solvang",
		Biography:    "Director of Tales from the Public Domain.",
		Birthday:     "",
		Deathday:     "",
		PlaceOfBirth: "",
		ProfilePath:  "",
		KnownForDept: "Directing",
		Popularity:   2.0,
		Gender:       1,
		ImdbID:       "",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           120,
		Name:         "Clara Voss",
		Biography:    "Film scholar who created and appears in Silent Film Classics.",
		Birthday:     "",
		Deathday:     "",
		PlaceOfBirth: "",
		ProfilePath:  "",
		KnownForDept: "Writing",
		Popularity:   2.4,
		Gender:       1,
		ImdbID:       "",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           121,
		Name:         "Theodore Mbeki",
		Biography:    "Narrator of Silent Film Classics.",
		Birthday:     "",
		Deathday:     "",
		PlaceOfBirth: "",
		ProfilePath:  "",
		KnownForDept: "Acting",
		Popularity:   2.8,
		Gender:       2,
		ImdbID:       "",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           122,
		Name:         "Anselm Richter",
		Biography:    "Documentary director of Silent Film Classics.",
		Birthday:     "",
		Deathday:     "",
		PlaceOfBirth: "",
		ProfilePath:  "",
		KnownForDept: "Directing",
		Popularity:   3.2,
		Gender:       2,
		ImdbID:       "",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           123,
		Name:         "Juno Castellane",
		Biography:    "Creator of The Lantern Society.",
		Birthday:     "",
		Deathday:     "",
		PlaceOfBirth: "",
		ProfilePath:  "",
		KnownForDept: "Writing",
		Popularity:   3.6,
		Gender:       1,
		ImdbID:       "",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           124,
		Name:         "Rosalind Okonkwo",
		Biography:    "Actress who plays The Archivist in The Lantern Society.",
		Birthday:     "",
		Deathday:     "",
		PlaceOfBirth: "",
		ProfilePath:  "",
		KnownForDept: "Acting",
		Popularity:   4.0,
		Gender:       1,
		ImdbID:       "",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           125,
		Name:         "Milo Tremaine",
		Biography:    "Actor who plays The Skeptic in The Lantern Society.",
		Birthday:     "",
		Deathday:     "",
		PlaceOfBirth: "",
		ProfilePath:  "",
		KnownForDept: "Acting",
		Popularity:   4.4,
		Gender:       2,
		ImdbID:       "",
		AlsoKnownAs:  []string{},
	},
	{
		ID:           126,
		Name:         "Ezra Lindahl",
		Biography:    "Director of The Lantern Society.",
		Birthday:     "",
		Deathday:     "",
		PlaceOfBirth: "",
		ProfilePath:  "",
		KnownForDept: "Directing",
		Popularity:   2.0,
		Gender:       2,
		ImdbID:       "",
		AlsoKnownAs:  []string{},
	},
}

// discPersonByID looks a person up by fake sequential id.
func discPersonByID(id int) (*DemoPerson, bool) {
	for _, p := range discPersons {
		if p.ID == id {
			return p, true
		}
	}
	return nil, false
}

// discPersonByName looks a person up by exact name; the credits table in
// data_credits.go is written in names and resolved once at init.
func discPersonByName(name string) (*DemoPerson, bool) {
	for _, p := range discPersons {
		if p.Name == name {
			return p, true
		}
	}
	return nil, false
}
